Portkey-AI/portkey-python-sdk

- portkey/api_resources/apis.py
- The generations API is made to accept the variables in case of template prompts with variables
Certain prompts may accept variables as inputs.
> feat: accepting variables in the generations API

- CHANGELOG.md
- portkey/api_resources/utils.py
- tests/anyscale_tests/test_anyscale_CodeLlama-34b-Instruct-hf.py
- tests/anyscale_tests/test_anyscale_Llama-2-13b-chat-hf.py
- tests/anyscale_tests/test_anyscale_Llama-2-70b-chat-hf.py
- tests/anyscale_tests/test_anyscale_Llama-2-7b-chat-hf.py
In this PR, we've introduced the integration with AnyScale and enhanced our OpenSchema validation to accommodate flexibility. Now, the `provider` field can accept any string, and the `mode` field can also take any string value.
**Changes:**
- Added AnyScale integration to broaden our supported services.
- Updated the OpenSchema validation to accept any string for the `provider` field.
- Enhanced OpenSchema to allow any string for the `mode` field, offering greater versatility.
**Rationale:**
By integrating with AnyScale and enhancing our OpenSchema validation, we provide users with more options and flexibility when configuring and interacting with our system. This expands the range of possible use cases and improves the overall user experience without having to upgrade their python …
> feat: anyscale integration & openschema for all integrations

- portkey/__init__.py
- portkey/api_resources/apis.py
- portkey/api_resources/base_client.py
- portkey/api_resources/utils.py
This pull request addresses the need to simplify configuration management by introducing support for configSlug instead of requiring the manual construction of the entire config within the codebase. By allowing users to reference pre-configured settings via a configSlug, we aim to reduce the amount of code users need to write and encourage the reuse of configurations across different codebases.
**Changes**
- Added a new feature that supports the usage of configSlug as a reference to pre-configured settings.
- Modified relevant code sections to incorporate this new feature.
Fixes: #29
> feat: Added support for config-slug in the apis

- README.md
> fix: Fixing the image refrerences in the readme file

- README.md
Fixing some nit-pick changes on the docs.
> fix: Minor updates on the docs

- portkey_ai/__init__.py
- portkey_ai/api_resources/__init__.py
- portkey_ai/api_resources/apis/__init__.py
- portkey_ai/api_resources/apis/generation.py
- portkey_ai/api_resources/client.py
- portkey_ai/version.py
**Title:** Rename prompt class to prompts
- Rename prompt class to prompts, to comply with docs.
It was a bug, didn't follow the documentation.
#61
> Rename prompt to prompts.

- setup.cfg
**Title:** update typing extensions version constraint in setup.cfg
- Update typing dependencies version constraints from strict ==4.7.1 to >=4.7.1,<5.0 to resolve dependency conflict with package like chroma
To avoid any dependency conflict with packages that internally require a higher version of typing dependencies
Closes #67 
Closes #66
> chore: update typing extensions version constraint

- portkey_ai/api_resources/utils.py
**Title:** update classes with latest `openai` signature
- Add `logprobs` and `top_logprobs` to ModelParams model. 
- Add `ToolCall` and `DeltaToolCall` (for stream) classes for response.
- Add `tools` and `tools_choice` to ModelParams.
- Add `tool_calls` to Message model to allow tool calls response.
- Make content optional in Message model to allow tool_calls response which does not send content as a string.
- To accomodate latest signature updates of openai like tool_calls and logprobs
- Closes #71
> feat: update classes with latest openai signature

- portkey_ai/api_resources/utils.py
**Title:** Add default values for Optional properties for pydantic v2 compatibility
- Add default None for Optional properties in GenericResponse class
To be compatible with the new Optional definition of pydantic v2
- Closes #73
> fix: add default value in optional field for pydantic v2 compatibility

- tests/test_assistants.py
- tests/test_async_chat_complete.py
- tests/test_async_complete.py
- tests/test_async_images.py
- tests/test_chat_complete.py
- tests/test_complete.py
- tests/test_images.py
- tests/test_threads.py
- tests/utils.py
**Title:** Fix test cases linting errors occuring during build
- Use `isinstance` instead of `type` in test cases
Fix errors occuring during make build
Closes #99
> fix: build errors in test cases

- setup.cfg
**Title:** Hotfix OpenAI dependency 
- adding OpenAI as install_requires 
#102
> hotfix: openAI as dependency

- portkey_ai/api_resources/types/assistant_type.py
- portkey_ai/api_resources/types/chat_complete_type.py
- portkey_ai/api_resources/types/complete_type.py
- portkey_ai/api_resources/types/embeddings_type.py
- portkey_ai/api_resources/types/generation_type.py
- portkey_ai/api_resources/types/image_type.py
- portkey_ai/api_resources/types/main_file_type.py
- portkey_ai/api_resources/types/models_type.py
- portkey_ai/api_resources/types/thread_message_type.py
- portkey_ai/api_resources/types/thread_run_type.py
- portkey_ai/api_resources/types/thread_type.py
**Title:** 
fix: private attribute changes for pydantic v1 compatibility
- Use PrivateAttr from pydantic for _headers in all class
- Pydantic v1 compatibility
- Fixes #115
> fix: private attribute changes for pydantic v1 compatibility

- .github/workflows/python-publish.yml
**Title:** Release workflow
- Issue: `mypy` was not installed for `make build` to run
- Not only for `mypy`, would have been an issue for `black` and `ruff` as well
- Have to run `make dev` while installing dependencies
Avoids the manual effort to publish the package
#159
> Release workflow

- portkey_ai/api_resources/types/chat_complete_type.py
**Title:** prompt rendor response type
- Added Union of string and Iterable Any for the content.message
Issue reported by user on Discord (https://discord.com/channels/1143393887742861333/1253676373302710335/1253827484160626788)
Closes #170
> Hotfix: prompt rendor response type

- portkey_ai/version.py
- setup.cfg
**Title:** Building Package issue
- /lib under Vendoring not being added to build 
- force adding in setup.cfg
Closes #176
> fix: /lib for vendoring

- portkey_ai/api_resources/client.py
**Title:** Default retries to zero
- Setting `max_retries = 0` where we initialise the client
To avoid default max retries which is equal to 3
Closes: #181
> Max Retries 

- portkey_ai/api_resources/types/complete_type.py
**Title:** 
Update types for token_logprobs and top_logprobs inside Completion Response
- Refer https://github.com/Portkey-AI/gateway/issues/463 for original issue report
OpenAI SDK returns the response object as is, so there is no type checking by Pydantic, it's inferred on the client side and hence doesn't fail withe openAI SDK
Whereas portkey-sdk manipulates the object and Pydantic check fails
Example OpenAI Response
```
{
"id": "cmpl-9nlcqIQdJrv3sqCf8L69Pn3LWrkMI",
"object": "text_completion",
"created": 1721648172,
"model": "davinci-002",
"choices": [
{
"text": "What is the current temperature in San Francisco? also set light brightness to 50 and color to warm white and these cool lights wont work in the car. It’s possible that your",
"index": 0, …
```
> Allow token_logprobs and top_logprobs List to have Objects of None type

- tests/virtual_keys_replacement.sh
**Title:**  Virtual Key Script
- updateing `virtual_key_replacement.sh`
Fixes: #183
>  virtual key script

- portkey_ai/api_resources/apis/audio.py
- portkey_ai/api_resources/apis/batches.py
- portkey_ai/api_resources/apis/chat_complete.py
- portkey_ai/api_resources/apis/complete.py
- portkey_ai/api_resources/apis/embeddings.py
- portkey_ai/api_resources/apis/fine_tuning.py
- portkey_ai/api_resources/apis/images.py
- portkey_ai/api_resources/apis/main_files.py
- portkey_ai/api_resources/apis/models.py
- portkey_ai/api_resources/apis/moderations.py
**Title:** `kwargs` in `extra_body`
- OpenAI client doesn't accept `kwargs`
- Passed `kwargs` in `extra_body`
Our SDK was not accepting and passing `safety_settings`
Fixes: #187
> hotfix: kwargs in extra_body

- portkey_ai/llamaindex/portkey_llama_callback_handler.py
**Title:** Llama Payload changes
- Handle event sub_question
- Refactor code for JSON serializable
- Ignore event list to be updated
Traces to capture known events.
Fixes: #210
> Llama payload

- setup.cfg
**Title:** Pydantic install_requires range
- Reducing the range of pydantic to >=1.10.0
Issue for a user for integration
Fixes: #232
> Pydantic install_requires

- portkey_ai/api_resources/apis/__init__.py
- portkey_ai/api_resources/apis/beta_chat.py
- portkey_ai/api_resources/types/api_keys_type.py
- portkey_ai/api_resources/types/assistant_type.py
- portkey_ai/api_resources/types/audio_types.py
- portkey_ai/api_resources/types/batches_type.py
- portkey_ai/api_resources/types/beta_chat_type.py
- portkey_ai/api_resources/types/chat_complete_type.py
- portkey_ai/api_resources/types/complete_type.py
- portkey_ai/api_resources/types/configs_type.py
- portkey_ai/api_resources/types/embeddings_type.py
- portkey_ai/api_resources/types/feedback_type.py
- portkey_ai/api_resources/types/fine_tuning_type.py
- portkey_ai/api_resources/types/generation_type.py
- portkey_ai/api_resources/types/image_type.py
- portkey_ai/api_resources/types/logs_type.py
- portkey_ai/api_resources/types/main_file_type.py
- portkey_ai/api_resources/types/models_type.py
- portkey_ai/api_resources/types/moderations_type.py
- portkey_ai/api_resources/types/thread_message_type.py
- portkey_ai/api_resources/types/thread_run_type.py
- portkey_ai/api_resources/types/thread_type.py
- portkey_ai/api_resources/types/upload_types.py
- portkey_ai/api_resources/types/user_invite_type.py
- portkey_ai/api_resources/types/vector_stores_type.py
- portkey_ai/api_resources/types/virtual_keys_type.py
- portkey_ai/api_resources/utils.py
- setup.cfg
**Title:** Pydantic versioning
- Handled case of user's pydantic v1 dependency 
- Added types for beta.chat.completion
- Added type for chat.completion
- Added extra="allow" for all the types
- Setting None as default value for the Optional Keys
- Adding more type classes for the Threads route
- Minimum required pydantic version 1.10.8 (advised to use 2.0 [suggested, as per pydantic docs])
User reported issue, pydantic version mismatch while using other SDKs
Closes: #247 #252
> Pydantic for v1 and v2

- Makefile
- portkey_ai/api_resources/apis/logger.py
- portkey_ai/api_resources/base_client.py
- portkey_ai/api_resources/client.py
- portkey_ai/api_resources/instrumentation/__init__.py
- portkey_ai/api_resources/instrumentation/crewai/__init__.py
- portkey_ai/api_resources/instrumentation/crewai/instrumentation.py
- portkey_ai/api_resources/instrumentation/crewai/patch.py
- portkey_ai/api_resources/instrumentation/langgraph/__init__.py
- portkey_ai/api_resources/instrumentation/langgraph/instrumentation.py
- portkey_ai/api_resources/instrumentation/langgraph/patch.py
- portkey_ai/api_resources/instrumentation/litellm/__init__.py
- portkey_ai/api_resources/instrumentation/litellm/instrumentation.py
- portkey_ai/api_resources/instrumentation/litellm/patch.py
- portkey_ai/api_resources/instrumentation/openai/__init__.py
- portkey_ai/api_resources/instrumentation/openai/instrumentation.py
- portkey_ai/api_resources/instrumentation/openai/patch.py
- portkey_ai/api_resources/instrumentation/portkey_span_exporter.py
- portkey_ai/api_resources/instrumentation/utils.py
- portkey_ai/api_resources/utils.py
- portkey_ai/utils/__init__.py
- portkey_ai/utils/hashing_utils.py
- portkey_ai/utils/json_utils.py
- setup.cfg
> instrumentation using monkey patching and open telemetry

- portkey_ai/api_resources/types/chat_complete_type.py
**Title:** Response 
- Changed the response type for chat completion content from Iterable to List
Issue while handling the 200 response type
Fixes: #294
> fix: list type for content

- portkey_ai/api_resources/apis/chat_complete.py
- portkey_ai/api_resources/apis/generation.py
**Title:** Headers in Prompt Completions
- Introducing extra_headers argument in prompts.completion.create()
- This helps to avoid the use of with_options for prompt completions call
Suggested by user. Helps to avoid creation of portkey client with with_options when custom headers are to be passed
Closes: #308
> Headers in Prompt Completions

- LICENSE
- setup.cfg
**Title:** SetuptoolsDeprecationWarning
- Update classifier
- Update License to 2025
Warning on `make build` fixed
Fixes: #333
> License warning

- portkey_ai/api_resources/apis/__init__.py
- portkey_ai/api_resources/apis/deleteMethod.py
- portkey_ai/api_resources/apis/getMethod.py
- portkey_ai/api_resources/apis/putMethod.py
- portkey_ai/api_resources/client.py
**Title:** GET, DELETE and PUT Support
- GET Support
- PUT Support
- DELETE Support
User asked for it 
Closes: #353
> GET, DELETE and PUT Support

- portkey_ai/api_resources/base_client.py
- portkey_ai/api_resources/utils.py
**Title:** Deprecation warning  (Pydantic)
- Replaces construct with model_construct
User reported the issue
Fixes: #373
> Construct warning pydantic
