Portkey-AI/portkey-python-sdk

CONTRIBUTING.md

fix: fixing the docs for local installation

---

portkey_ai/version.py

**Title:** Bump version to 1.1.2 for new release
- Bumps the version to 1.1.2
To create a new release and update the package
Closes #67 
Closes #66

feat: bump version for release

---

portkey_ai/version.py

**Title:** Release 1.1.3
- Closes #70

feat: release 1.1.3

---

portkey_ai/version.py

**Title:** Bump version to 1.1.4
- Closes #73

Bump version to 1.1.4

---

setup.cfg

Relax `mypy` version constraint

---

portkey_ai/version.py

**Title:** bump version to 1.1.5
- Closes #76

feat: bump version to 1.1.5

---

portkey_ai/api_resources/apis/embeddings.py

**Title:** allow new embeddings params in create method
- Add all the know params in create method definition for embeddings
- Allow **kwargs to support new params in future without errors
- To support new embeddings params
- Closes #79

feat: allow new embeddings params like dimensions

---

portkey_ai/version.py

**Title:** Release 1.1.6
- Bump version to 1.1.6
- Closes #79

feat: bump version to 1.1.6

---

portkey_ai/version.py

**Title:** Release 1.1.7
- Update version to 1.1.7
- #33

feat: release-1.1.7

---

portkey_ai/version.py

feat: release 1.2.0

---

tests/test_async_images.py
tests/test_images.py

**Title:** Minor code formatting using `black` for test cases
Related to #89

chore: test case formatting

---

portkey_ai/version.py

**Title:** Release v1.2.1
- Bump version to v1.2.1

feat: release 1.2.1

---

portkey_ai/api_resources/client.py

**Title:** Better DevEx
- Suggestions for beta sub methods
- Go to definitions for beta and sub methods now possible
#105

class Beta sub methods

---

portkey_ai/version.py

feat: release 1.2.2

---

README.md

Add OpenAI SDK compliant blurb to readme

---

portkey_ai/version.py

**Title:** Release 1.2.3
- Prompt Response type

feat: release 1.2.3

---

setup.cfg

**Title:** Black package Dependency conflict
- Black package in both install requires and extra require. Can be removed from install requires
https://discord.com/channels/1143393887742861333/1144592558132035655/1227709106832281772
#112

black package 

---

portkey_ai/api_resources/apis/api_resource.py
portkey_ai/api_resources/apis/create_headers.py
portkey_ai/api_resources/apis/feedback.py
portkey_ai/api_resources/base_client.py
portkey_ai/api_resources/types/feedback_type.py
portkey_ai/api_resources/utils.py

**Title:** Lint Fix
- fixing linting issues
- for all the merginnFeatures branch
#139

fix: linting issues

---

portkey_ai/api_resources/apis/create_headers.py

**Title:** Sanity Check
- headers being printed
#140

Sanity Check

---

portkey_ai/api_resources/types/chat_complete_type.py

**Title:** Azure Chat Completion Response type
- Few field were not optional
- Chat completion response type modified
Issue reported on discord by a user
#144

hotfix/ chat completion for azure

---

portkey_ai/api_resources/base_client.py
portkey_ai/api_resources/client.py

**Title:** Latency Issue
- Stopped reconnection of http client on with_options
- passing http client to openai client
- closing the old http client
Issue causing latency in production for enterprise user
#148

Latency Issue

---

portkey_ai/api_resources/base_client.py
portkey_ai/api_resources/client.py
portkey_ai/api_resources/utils.py

**Title:** Request_timeout header
- Support for request-timeout as header
#164

request_timeout header

---

portkey_ai/api_resources/base_client.py
portkey_ai/api_resources/client.py
portkey_ai/api_resources/types/chat_complete_type.py

**Title:** Vertex Changes
- allowed header: strict_open_ai_compliance
- Change the chatCompletion response type to allow extra fields
Closes: #191

Vertex Changes

---

portkey_ai/langchain/portkey_langchain_callback_handler.py

**Title:** Langchain Events
- Removed support for logging the following events:
- - on_text
- - on_agent_action
- - on_agent_finish
- - on_chat_model_start
Extra noise for traces
Fixes: #203

Langchain Events

---

portkey_ai/api_resources/apis/audio.py

**Title:** Stream for Audio Speech
- Handled case for stream for Audio Speech
Requested by users
Fixes: #213

Stream for Audio Speech

---

portkey_ai/api_resources/base_client.py
portkey_ai/api_resources/client.py
portkey_ai/api_resources/utils.py

**Title:** Anthropic Beta Header
- Passing anthropic beta as optional string in the constructor
Fixes: #217  and #185

anthropic-beta header

---

portkey_ai/api_resources/base_client.py
portkey_ai/api_resources/client.py
portkey_ai/api_resources/utils.py

**Title:** Provider Headers
- Headers to be added:
-- mistral-fim-completion
-- azure-endpoint-name
-- anthropic-version
Closes: #221

Provider Headers (azure, anthropic and mistral)

---

setup.cfg

**Title:** <Brief Description of Changes>
- Detailed change 1
- Detailed change 2
- ...
<Why this change is necessary or beneficial>
Mypy is a dev dependency. Should be removed from dependencies.
#<issue-number>

Remove `mypy` from dependencies

---

portkey_ai/_vendor/openai/_exceptions.py
portkey_ai/api_resources/base_client.py
portkey_ai/api_resources/global_constants.py
portkey_ai/api_resources/utils.py

**Title:** Setup Check for selfhosted gateway
- Set localhost:8787 as baseUrl is base_url and api_key not found
- Check if localhost is running or not and then send error message accordingly
Closes: #230  and  #136 
TODO:

 BaseURL and APIKey Optional

---

setup.cfg

**Title:** <Brief Description of Changes>
- Detailed change 1
- Detailed change 2
- ...
<Why this change is necessary or beneficial>
#<issue-number>

fix: remove duplicate dependencies in `extras_require`

---

portkey_ai/api_resources/apis/threads.py

**Title:** Support for stream in Threads
- Adding stream in runs.create
- Adding stream in create_and_run
Closes: #245

feat: stream for threads and runs

---

portkey_ai/api_resources/types/assistant_type.py
portkey_ai/api_resources/types/audio_types.py
portkey_ai/api_resources/types/batches_type.py
portkey_ai/api_resources/types/chat_complete_type.py
portkey_ai/api_resources/types/complete_type.py
portkey_ai/api_resources/types/embeddings_type.py
portkey_ai/api_resources/types/fine_tuning_type.py
portkey_ai/api_resources/types/image_type.py
portkey_ai/api_resources/types/main_file_type.py
portkey_ai/api_resources/types/models_type.py
portkey_ai/api_resources/types/moderations_type.py
portkey_ai/api_resources/types/thread_message_type.py
portkey_ai/api_resources/types/thread_run_type.py
portkey_ai/api_resources/types/upload_types.py
portkey_ai/api_resources/types/vector_stores_type.py

**Title:** Optional response type
- Making all fields in the response type classes as truly optional
Issue while using vendors other than Azure OpenAI
Closes: #274

Optional Response Types

---

portkey_ai/api_resources/client.py

Correct import error message in case of instrumentation

Import Error Message

---

portkey_ai/api_resources/apis/batches.py

**Title:**  Batches Output
- Supporting batches.output
Closes: #297

feat: support for batches output

---

portkey_ai/_vendor/openai/_base_client.py

FIxes Portkey-AI/portkey-python-sdk#301

Fix "Retry for timeout"

---

.github/workflows/ci.yml
.github/workflows/dependency-review.yml
.github/workflows/python-publish.yml

Deprecated Actions: 
actions/checkout
actions/setup-python
actions/cache
actions/dependency-review-action

Workflow File

---

portkey_ai/api_resources/apis/create_headers.py
portkey_ai/api_resources/base_client.py
portkey_ai/api_resources/client.py
portkey_ai/api_resources/utils.py

**Title:** Headers needed for finetune
Support for: 
```
x-portkey-vertex-storage-bucket-name
x-portkey-provider-file-name
x-portkey-provider-model
x-portkey-aws-s3-bucket
x-portkey-aws-s3-object-key
x-portkey-aws-bedrock-model
```
Closes: #304

Headers for Finetune

---

portkey_ai/langchain/portkey_langchain_callback_handler.py
portkey_ai/llamaindex/portkey_llama_callback_handler.py

**Title:** Custom base_url for callback handlers
- Provision to allow users to send their base_url in the langchain and llama index callback handlers 
Users want to have logs pushed to their system
Closes: #310

Custom base_url for Callback Handlers

---

portkey_ai/api_resources/apis/generation.py
portkey_ai/api_resources/types/chat_complete_type.py
portkey_ai/api_resources/types/complete_type.py

**Title:** get method support for chat completion 
- To handle extra keys coming in case of streaming response
- Added get() in each class of response type
Closes: #314

get() for Chat Completion Response

---

portkey_ai/api_resources/base_client.py
portkey_ai/api_resources/global_constants.py

**Title:** Httpx Max Connections
- Overriding the default values of httpx limits to `max_connections = 1000` and `max_keepalive_connections = 100`
Reduces time taken from ~30 seconds  to  ~6 seconds (benchmark 1000 requests)
Closes: #317

Httpx Max Connections

---

portkey_ai/api_resources/streaming.py

**Title:** Context Manager for Stream and AsyncStream Class
- added methods:
-> `__enter__`
-> `__exit__ `
-> `__aenter__`
-> ` __aexit__`
-> `close`
Closes: #312

Context Manager

---

portkey_ai/api_resources/base_client.py
portkey_ai/api_resources/client.py
portkey_ai/api_resources/utils.py

**Title:** Fireworks Header
- Support for: `fireworks_account_id`
Closes: #323

Fireworks Header 

---

portkey_ai/api_resources/apis/configs.py

**Title:** Config Del: id and slug
- Accepting slug and id for now
- Added deprecation warning with it as well
Maintaining uniformity 
Closes: #326

Delete Config ID and SLUG

---

portkey_ai/__init__.py
portkey_ai/api_resources/__init__.py
portkey_ai/api_resources/apis/__init__.py
portkey_ai/api_resources/apis/collections.py
portkey_ai/api_resources/apis/generation.py
portkey_ai/api_resources/apis/labels.py
portkey_ai/api_resources/client.py
portkey_ai/api_resources/utils.py

Prompts Endpoints

---

setup.cfg

**Title:** Hatch Pytest
- options package set to the top level portkey_ai directory 
User facing import issues while running pytest
Closes: #343

FIX: Hatch pytest

---

portkey_ai/api_resources/apis/audio.py

**Title:** Print Statement
- Removed Print statement
Closes: #345

chore: remove audio duration print statement
